naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: hSofN2Q0B3nqf48pbcAd
    secret: YO3hotzLJA
